	CDTCommon::DEF* D1;
	CDTCommon::DEF D2;
	D1 = new CDTCommon::DEF;
	D1->Name="Hello";
	D1->TListQ=2;
	D1->TList.setUbound (1);
	D1->TList[1].TTo="a";
	D1->TList[0].TTo="0";
	D2=*D1;
	delete D1;
	wLine(D2.Name);
	wLine(D2.TList[1].TTo);
	wLine(D2.TList[0].TTo);
	wLine("completed");